[tool.poetry]
name = "qmlease"
version = "3.0.4a3"
homepage = "https://github.com/likianta/qmlease"
description = "A flexible toolkit for Python programmer to efficiently develop QML graphical user interface."
readme = "README.md"
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "default"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "*"
lambda-ex = "^1.1.0"
lk-logger = "^5.4.8"
lk-utils = "^2.5.5"
qtpy = "^2.3.0"
typing-extensions = "*"
pyside6 = { version = "^6.4,<6.5", python = ">=3.8,<3.12", optional = true }
pyside2 = { version = "^5.15", python = ">=3.8,<3.11", optional = true }

[tool.poetry.extras]
qt6 = ["pyside6"]  # pip install qmlease[qt6]
qt5 = ["pyside2"]  # pip install qmlease[qt5]

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
